project:
  type: website

website:
  title: "Khang Thai"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Page
      - href: projects.qmd
        text: Projects
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual


execute: 
  freeze: auto